name: AlyasRobinHood
main: LittleBigMC\RBH\RBH

author: CodeBreak

version: 1.0.1-indev

api: [3.0.0-ALPHA11, 3.0.0-ALPHA12]

commands:
    r:
        usage: /mb <leave-make>
        description: MicroBattles-Commands
    lang:
        usage: /lang <en>
        description: SkyWars-English-Lang
    rankmb:
        usage: /rankmb
        description: MicroBattles-Commands
    mbstart:
        usage: /mbstart
        description: MicroBattles-Force start
