name: AlyasRobinHood
main: LittleBigMC\RBH\RBH
author: CodeBreak
version: 1.0.2-indev
api: [3.0.0, 3.5.2, 4.0.0]

commands:
    rbh:
        usage: /rbh <leave-make>
        description: Robinhood main cmd
    rbhstart:
        usage: /rbhstart
        description: Robinhood force start
